title: <p align="center"> Diego Calderon </p>

logo: "/images/picture.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/diegocalderon/">LinkedIn</a> |
  <a href="https://github.com/romilan24">GitHub</a>
  </p>
  
  <p align="justify">
  Experienced engineer specializing in forecasting, machine learning, deep learning, and optimization.
  <br><br>
  Machine Learning modeling in the Energy and Finance industries.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
